[package]
name = "mtret"
version = "0.1.1"
entrypoint = "lib.typ"
authors = ["hinshiba"]
license = "MIT"
description = "Modular Typst REport Template for ja"
repository = "https://github.com/hinshiba/MTReT"
